# The native FreeBSD build of libgif-compat.so; the zedBSD build remains in Makefile.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
KEILAND_FREEBSD_GIF_COMPAT_SOURCES := userland/base/libgif-compat/decode.c \
	userland/base/libgif-compat/lzw.c
$(eval $(call KEILAND_FREEBSD_LIBRARY,gif-compat,libgif-compat.so,$(KEILAND_FREEBSD_GIF_COMPAT_SOURCES),,-lm,userland/base/libgif-compat/exports.map))
