#!/bin/sh
# ws115-p009: build the xdg-shell probe for the target.  Its xdg-shell code is
# generated by the build machine's upstream wayland-scanner from the
# wayland-protocols package's XML, as GTK's is; the probe links with zedBSD's
# libwayland-client (the wayland-client stage of userland/desktop/libwayland).
# Prints the extra files that put the probe into a test image.
# Run from the repository root after `make wayland-protocols wayland-client`.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
#
# usage: plan/ws115/tests/xdg-probe.sh <cross-dir> <package-workroot> <work-dir> [machine]
set -eu

test $# -ge 3 || { echo "usage: ${0##*/} <cross-dir> <package-workroot> <work-dir> [machine]" >&2; exit 1; }
cross=$1
workroot=$(CDPATH= cd -- "$2" && pwd)
mkdir -p "$3"
work=$(CDPATH= cd -- "$3" && pwd)
machine=${4:-amd64}
source=$(CDPATH= cd -- "$(dirname -- "$0")/xdg-probe" && pwd)

# The protocol code, from the packaged XML, by upstream wayland-scanner.
xml="$workroot/wayland-protocols/stage/usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml"
wayland-scanner --version
wayland-scanner client-header "$xml" "$work/xdg-shell-client-protocol.h"
wayland-scanner private-code "$xml" "$work/xdg-shell-protocol.c"

# The probe, against the sysroot's Wayland headers and the staged library.
"$cross/bin/zedbsd-clang" -std=gnu11 -Wall -Wextra -Werror -O2 -I"$work" \
	-o "$work/xdg-probe" "$source/xdg-probe.c" "$work/xdg-shell-protocol.c" \
	-L"$workroot/wayland-client/stage/usr/lib" -lwayland-client
python3 tools/build/check-dynamic-elf.py --machine "$machine" --role application \
	--needed libwayland-client.so --needed libc.so "$work/xdg-probe"

echo "ZEDBSD_TEST_EXTRA_FILES=--file /usr/bin/xdg-probe=$work/xdg-probe --mode /usr/bin/xdg-probe=0755"
