# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent FreeBSD build of ime; source membership mirrors the target package.
KEILAND_FREEBSD_IME_SOURCES := userland/desktop/ime/main.c \
	userland/desktop/ime/method.c \
	userland/desktop/ime/keys.c \
	userland/desktop/ime/output.c \
	userland/desktop/ime/engine-direct.c \
	userland/desktop/ime/ja-kana.c \
	userland/desktop/ime/ja-romaji.c \
	userland/desktop/ime/ja-dict.c \
	userland/desktop/ime/ja-user.c \
	userland/desktop/ime/ja-inflect.c \
	userland/desktop/ime/ja-segment.c \
	userland/desktop/ime/ja-engine.c \
	userland/desktop/ime/ja-keys.c \
	userland/desktop/ime/popup.c
$(eval $(call KEILAND_FREEBSD_PROGRAM,keiland-ime,libexec,$(KEILAND_FREEBSD_IME_SOURCES),libkeiui.so libkeiland.so libtruetype.so libpng-compat.so libz-compat.so libwayland-client.so libvulkan.so.1,-lm -pthread))
