# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent Linux build of ime; source membership mirrors the target package.
KEILAND_LINUX_IME_SOURCES := userland/desktop/ime/main.c \
	userland/desktop/ime/method.c \
	userland/desktop/ime/keys.c \
	userland/desktop/ime/output.c \
	userland/desktop/ime/engine-direct.c \
	userland/desktop/ime/ja-kana.c \
	userland/desktop/ime/ja-romaji.c \
	userland/desktop/ime/ja-dict.c \
	userland/desktop/ime/ja-user.c \
	userland/desktop/ime/ja-inflect.c \
	userland/desktop/ime/ja-segment.c \
	userland/desktop/ime/ja-engine.c \
	userland/desktop/ime/ja-keys.c
$(eval $(call KEILAND_LINUX_PROGRAM,keiland-ime,libexec,$(KEILAND_LINUX_IME_SOURCES),libwayland-client.so,))
