# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The portable Vulkan demo uses the same four sources on both operating systems.
$(eval $(call KEILAND_LINUX_PROGRAM,vkdemo,bin,userland/desktop/vkdemo/main.c userland/desktop/vkdemo/renderer.c userland/desktop/vkdemo/display.c userland/base/common/sha256.c,libvulkan.so.1,-lm))
