# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The portable viewer installs the same converted model and textures under the Linux prefix.
KEILAND_MVIEW_SOURCES := userland/desktop/mview/main.c userland/desktop/mview/window.c \
	userland/desktop/mview/renderer.c userland/desktop/mview/model.c \
	userland/desktop/mview/camera.c userland/desktop/mview/input.c
$(eval $(call KEILAND_LINUX_PROGRAM,mview,bin,$(KEILAND_MVIEW_SOURCES),libwayland-client.so libvulkan.so.1,-lm))
$(eval $(call KEILAND_LINUX_DATA,share/mview/qs40/model.txt,userland/desktop/mview/models/qs40/model.txt))
KEILAND_MVIEW_TEXTURES := $(sort $(wildcard userland/desktop/mview/models/qs40/tex/*.pam))
$(foreach texture,$(KEILAND_MVIEW_TEXTURES),$(eval $(call KEILAND_LINUX_DATA,share/mview/qs40/tex/$(notdir $(texture)),$(texture))))
