#!/usr/bin/env python3
# zedBSD
# Copyright (C) 2026 Awe Morris
#
# SPDX-License-Identifier: Zlib
#
# Generates ambiguous.h, the table of the characters whose East Asian Width
# is A (Ambiguous), for terminal's "Treat Ambiguous-Width Characters as
# Wide" (ws128-p009).
#
# The data are the Unicode Character Database's own files, fetched from
# unicode.org and checked against the SHA-256 recorded below:
#
#   ambiguous-gen.py --fetch            downloads into ./ucd (not committed)
#   ambiguous-gen.py [UCD_DIR] > ambiguous.h
#
# A characters whose general category is Mn, Me (combining marks), Cf
# (format characters) or Cc (controls) are left out: they take no cell of
# their own and must never become two cells wide.

import hashlib
import os
import sys
import urllib.request

UNICODE_VERSION = "17.0.0"
BASE_URL = "https://www.unicode.org/Public/%s/ucd/" % UNICODE_VERSION
FILES = {
    "EastAsianWidth.txt": "ea7ce50f3444a050333448dffef1cadd9325af55cbb764b4a2280faf52170a33",
    "UnicodeData.txt": "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c",
}
EXCLUDED_CATEGORIES = ("Mn", "Me", "Cf", "Cc")


def fetch(directory):
    """Downloads the data files and checks their hashes."""
    os.makedirs(directory, exist_ok=True)
    for name in FILES:
        with urllib.request.urlopen(BASE_URL + name, timeout=60) as response:
            data = response.read()
        with open(os.path.join(directory, name), "wb") as output:
            output.write(data)
    check(directory)


def check(directory):
    """Refuses data files whose hash is not the recorded one."""
    for name, expected in FILES.items():
        with open(os.path.join(directory, name), "rb") as data:
            digest = hashlib.sha256(data.read()).hexdigest()
        if digest != expected:
            sys.exit("%s: sha256 %s, expected %s" % (name, digest, expected))


def categories(directory):
    """Reads every assigned code point's general category (ranges included)."""
    table = {}
    first = None
    with open(os.path.join(directory, "UnicodeData.txt"), encoding="utf-8") as data:
        for line in data:
            fields = line.split(";")
            code = int(fields[0], 16)
            name = fields[1]
            category = fields[2]
            if name.endswith(", First>"):
                first = code
                continue
            if name.endswith(", Last>"):
                for value in range(first, code + 1):
                    table[value] = category
                first = None
                continue
            table[code] = category
    return table


def ambiguous(directory):
    """Lists the code points whose East Asian Width is A."""
    points = []
    with open(os.path.join(directory, "EastAsianWidth.txt"), encoding="utf-8") as data:
        for line in data:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            span, width = [part.strip() for part in line.split(";")]
            if width != "A":
                continue
            if ".." in span:
                low, high = [int(part, 16) for part in span.split("..")]
            else:
                low = high = int(span, 16)
            points.extend(range(low, high + 1))
    return points


def ranges(points):
    """Merges sorted code points into inclusive ranges."""
    merged = []
    for point in sorted(points):
        if merged and merged[-1][1] + 1 == point:
            merged[-1][1] = point
        else:
            merged.append([point, point])
    return merged


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--fetch":
        fetch("ucd")
        return
    directory = "ucd"
    if len(sys.argv) > 1:
        directory = sys.argv[1]
    check(directory)
    category = categories(directory)
    points = [p for p in ambiguous(directory) if category.get(p, "Cn") not in EXCLUDED_CATEGORIES]
    merged = ranges(points)

    out = sys.stdout
    out.write("/*\n * zedBSD\n * Copyright (C) 2026 Awe Morris\n *\n * SPDX-License-Identifier: Zlib\n */\n\n")
    out.write("/*\n")
    out.write(" * The characters whose East Asian Width is A (Ambiguous), as sorted\n")
    out.write(" * inclusive ranges, for width.c's binary search.\n")
    out.write(" *\n")
    out.write(" * Generated by ambiguous-gen.py from the Unicode Character Database %s:\n" % UNICODE_VERSION)
    for name, digest in FILES.items():
        out.write(" *   %s sha256 %s\n" % (name, digest))
    out.write(" * Mn, Me, Cf and Cc characters are left out.  Do not edit by hand.\n")
    out.write(" */\n\n")
    out.write("#ifndef KEILAND_TERMINAL_AMBIGUOUS_H\n#define KEILAND_TERMINAL_AMBIGUOUS_H\n\n")
    out.write("/* How many ranges the table has (%d code points). */\n" % len(points))
    out.write("#define AMBIGUOUS_RANGES\t%dU\n\n" % len(merged))
    out.write("/*\n * The ranges, lowest first; they neither overlap nor touch.\n *\n")
    out.write(" * The table is constant data for the whole run.\n */\n")
    out.write("static const struct terminal_width_range ambiguous_ranges[AMBIGUOUS_RANGES] = {\n")
    for low, high in merged:
        out.write("\t{ 0x%05xU, 0x%05xU },\n" % (low, high))
    out.write("};\n\n#endif\n")


if __name__ == "__main__":
    main()
