# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent FreeBSD build of terminal; source membership mirrors the target package.
KEILAND_FREEBSD_TERMINAL_SOURCES := userland/desktop/terminal/main.c \
	userland/desktop/terminal/screen.c \
	userland/desktop/terminal/keys.c \
	userland/desktop/terminal/font.c \
	userland/desktop/terminal/render.c \
	userland/desktop/terminal/window.c \
	userland/desktop/terminal/menu.c \
	userland/desktop/terminal/clipboard.c \
	userland/desktop/terminal/tabs.c \
	userland/desktop/terminal/primary.c \
	userland/desktop/terminal/touch.c
$(eval $(call KEILAND_FREEBSD_PROGRAM,terminal,bin,$(KEILAND_FREEBSD_TERMINAL_SOURCES),libkeiui.so libkeiland.so libwayland-client.so libtruetype.so libvulkan.so.1,-lm -lutil))
