# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent FreeBSD build of the System Monitor; source membership mirrors the target package.
KEILAND_FREEBSD_MONITOR_SOURCES := userland/desktop/monitor/main.c \
	userland/desktop/monitor/source.c \
	userland/desktop/monitor/history.c \
	userland/desktop/monitor/rules.c \
	userland/desktop/monitor/format.c \
	userland/desktop/monitor/atlas.c \
	userland/desktop/monitor/scene.c \
	userland/desktop/monitor/render.c
$(eval $(call KEILAND_FREEBSD_PROGRAM,monitor,bin,$(KEILAND_FREEBSD_MONITOR_SOURCES),libkeiui.so libkeiland.so libwayland-client.so libtruetype.so libvulkan.so.1 libkeiland-compat.a,-lm))
