#!/bin/sh
# Generate the Meson entry points external packages are given.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
#
# gen-cross-toolchain.sh has already written the compiler and binary-utility
# wrappers into <cross-dir>/bin; they carry the target, the sysroot, the user
# ABI macro and the link contract.  Meson is given those same wrappers through
# a cross file, so the contract still lives in one place and this file only
# names them.  Three things are written:
#
#   <cross-dir>/meson-cross.ini     the target machine, for --cross-file
#   <cross-dir>/meson-native.ini    the build machine, for --native-file
#   <cross-dir>/bin/zedbsd-pkg-config
#                                   pkg-config that sees only the packages a
#                                   build declares, never the build machine's
#
# usage: gen-meson-cross.sh <triple> <cross-dir>
set -eu

test $# -eq 2 || {
	echo "usage: ${0##*/} <triple> <cross-dir>" >&2
	exit 1
}

triple=$1
outdir=$2
bin="$outdir/bin"

# The wrappers are this file's inputs; without them a cross file would name
# programs that do not exist and Meson would fail much later and less clearly.
for tool in clang clang++ ar nm strip objcopy readelf ranlib; do
	test -x "$bin/zedbsd-$tool" || {
		echo "${0##*/}: missing $bin/zedbsd-$tool (run gen-cross-toolchain.sh first)" >&2
		exit 1
	}
done

# Meson describes a machine by CPU family and CPU.  The families are Meson's
# own names (reference tables, "CPU families"), not the triple's.
case $triple in
x86_64-*)
	cpu_family=x86_64
	cpu=x86_64
	;;
i386-*)
	cpu_family=x86
	cpu=i686
	;;
aarch64-*)
	cpu_family=aarch64
	cpu=aarch64
	;;
*)
	echo "${0##*/}: unsupported triple: $triple" >&2
	exit 1
	;;
esac

host_pkg_config=$(command -v pkg-config) || {
	echo "${0##*/}: the build machine has no pkg-config" >&2
	exit 1
}

# ------------------------------------------------------------ pkg-config

# The packages are staged one directory each (<workroot>/<name>/stage/usr)
# and their .pc files name /usr, sometimes through ${prefix} and sometimes
# literally (zlib's exec_prefix, for one).  A build therefore sees its
# dependencies through one directory of its own, the view, which holds
# symbolic links to every file of the stages it declares
# (<view>/usr/...); external.mk makes it.  pkg-config is given the view as
# its sysroot, so every /usr path of every .pc file lands in the view
# however it was written.  The view's location comes from the build that
# runs this, in ZEDBSD_PKG_CONFIG_VIEW; without one, nothing is visible.
# The build machine's own .pc files are never read: PKG_CONFIG_LIBDIR
# replaces the default search path rather than adding to it.  The system
# directory lists are emptied, because pkg-config would otherwise drop
# -I/usr/include and -L/usr/lib as directories the compiler searches anyway,
# which is true of the build machine and not of the view.
mkdir -p "$bin"
cat > "$bin/zedbsd-pkg-config" <<WRAPPER
#!/bin/sh
# Generated by userland/packages/tools/gen-meson-cross.sh.  Do not edit.
set -eu

zedbsd_view=\${ZEDBSD_PKG_CONFIG_VIEW-}
if [ -z "\$zedbsd_view" ]; then
	zedbsd_view='$outdir/no-view'
fi

unset PKG_CONFIG_PATH
PKG_CONFIG_LIBDIR="\$zedbsd_view/usr/lib/pkgconfig:\$zedbsd_view/usr/share/pkgconfig"
PKG_CONFIG_SYSROOT_DIR=\$zedbsd_view
PKG_CONFIG_SYSTEM_INCLUDE_PATH='$outdir/no-view/include'
PKG_CONFIG_SYSTEM_LIBRARY_PATH='$outdir/no-view/lib'
export PKG_CONFIG_LIBDIR PKG_CONFIG_SYSROOT_DIR
export PKG_CONFIG_SYSTEM_INCLUDE_PATH PKG_CONFIG_SYSTEM_LIBRARY_PATH
exec '$host_pkg_config' "\$@"
WRAPPER
chmod +x "$bin/zedbsd-pkg-config"

# ------------------------------------------------------------ cross file

# There is no exe_wrapper: a target program cannot run on the build machine,
# and needs_exe_wrapper tells a project not to try.  sys_root is left unset on
# purpose.  Meson would hand it to pkg-config as PKG_CONFIG_SYSROOT_DIR, which
# the wrapper above sets to the build's view, and the compiler wrappers
# already pass --sysroot themselves.  wrap_mode keeps a missing dependency from being
# fetched from the network: a build either finds the declared stages or stops.
cat > "$outdir/meson-cross.ini" <<CROSS
# zedBSD Meson cross file.  Generated by gen-meson-cross.sh; do not edit.
[binaries]
c = '$bin/zedbsd-clang'
cpp = '$bin/zedbsd-clang++'
ar = '$bin/zedbsd-ar'
nm = '$bin/zedbsd-nm'
ranlib = '$bin/zedbsd-ranlib'
strip = '$bin/zedbsd-strip'
objcopy = '$bin/zedbsd-objcopy'
readelf = '$bin/zedbsd-readelf'
pkg-config = '$bin/zedbsd-pkg-config'

[host_machine]
system = 'zedbsd'
kernel = 'zedbsd'
cpu_family = '$cpu_family'
cpu = '$cpu'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
default_library = 'shared'
wrap_mode = 'nodownload'
CROSS

# ------------------------------------------------------------ native file

# Programs that run during the build (code generators, the host's own glib
# tools, wayland-scanner) are build-machine programs.  Naming the build
# machine's compiler and pkg-config here keeps Meson from reaching for the
# cross wrappers when a project asks for something native.
cat > "$outdir/meson-native.ini" <<NATIVE
# zedBSD Meson native file.  Generated by gen-meson-cross.sh; do not edit.
[binaries]
c = 'cc'
cpp = 'c++'
pkg-config = '$host_pkg_config'
NATIVE

echo "meson cross files: $outdir"
