#!/usr/bin/env python3
# zedBSD
# Copyright (C) 2026 Awe Morris
# SPDX-License-Identifier: Zlib
"""Generates the Unicode case mapping tables.

  gen-unicode-case.py UnicodeData.txt SpecialCasing.txt OUTPUT.c

The two files are the Unicode Character Database's (Unicode 16.0.0),
downloaded and checked by tools/regenerate.sh; they are not kept in the
source tree, and the output (base/unicode-case-table.c) is committed.  The
output has, each sorted by code point:

  wb_case_lower / wb_case_upper       the simple (one to one) mappings
  wb_case_lower_full / wb_case_upper_full
                                      SpecialCasing's unconditional mappings
                                      to more than one code point (or to
                                      another one than the simple mapping)
  wb_case_cased / wb_case_ignorable   ranges of the Cased and
                                      Case_Ignorable properties as the
                                      general categories give them (Lu, Ll,
                                      Lt; Mn, Me, Cf, Lm, Sk and the MidLetter
                                      punctuation), for the final sigma rule
"""

import sys

MID_LETTER = [0x0027, 0x002E, 0x003A, 0x00B7, 0x0387, 0x055F, 0x05F4, 0x2018, 0x2019, 0x2024, 0x2027, 0xFE13,
              0xFE52, 0xFE55, 0xFF07, 0xFF0E, 0xFF1A]


def read_unicode_data(path):
    lower = {}
    upper = {}
    categories = {}
    first = None
    with open(path, encoding="utf-8") as stream:
        for line in stream:
            fields = line.rstrip("\n").split(";")
            point = int(fields[0], 16)
            name = fields[1]
            category = fields[2]
            if name.endswith(", First>"):
                first = point
                continue
            if name.endswith(", Last>"):
                for code in range(first, point + 1):
                    categories[code] = category
                first = None
                continue
            categories[point] = category
            if fields[12]:
                upper[point] = int(fields[12], 16)
            if fields[13]:
                lower[point] = int(fields[13], 16)
    return lower, upper, categories


def read_special_casing(path):
    lower = {}
    upper = {}
    with open(path, encoding="utf-8") as stream:
        for line in stream:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [field.strip() for field in line.split(";")]
            if len(fields) > 4 and fields[4]:
                continue
            point = int(fields[0], 16)
            lower_points = [int(value, 16) for value in fields[1].split()]
            upper_points = [int(value, 16) for value in fields[3].split()]
            if lower_points != [point]:
                lower[point] = lower_points
            if upper_points != [point]:
                upper[point] = upper_points
    return lower, upper


def ranges(points):
    result = []
    for point in sorted(points):
        if result and result[-1][1] + 1 == point:
            result[-1][1] = point
        else:
            result.append([point, point])
    return result


def main():
    data, special, output = sys.argv[1], sys.argv[2], sys.argv[3]
    lower, upper, categories = read_unicode_data(data)
    lower_full, upper_full = read_special_casing(special)
    cased = [point for point, category in categories.items() if category in ("Lu", "Ll", "Lt")]
    ignorable = [point for point, category in categories.items() if category in ("Mn", "Me", "Cf", "Lm", "Sk")]
    ignorable = sorted(set(ignorable) | set(MID_LETTER))

    lines = []
    lines.append("/*")
    lines.append(" * Generated by userland/desktop/libbrowser/tools/gen-unicode-case.py; do not edit.")
    lines.append(" * Regenerate with userland/desktop/libbrowser/tools/regenerate.sh, which")
    lines.append(" * pins the files' URLs and SHA-256.")
    lines.append(" *")
    lines.append(" * From the Unicode Character Database 16.0.0 (UnicodeData.txt,")
    lines.append(" * SpecialCasing.txt).  Copyright (C) 1991-2026 Unicode, Inc.  Distributed")
    lines.append(" * under the Unicode License V3 (https://www.unicode.org/license.txt): the")
    lines.append(" * copyright and permission notice appears with all copies of the data files,")
    lines.append(" * in userland/base/licenses/browser/Unicode-License-V3, which is")
    lines.append(" * installed as /usr/share/licenses/browser/Unicode-License-V3.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "base/unicode.h"')
    lines.append("")

    def simple(name, table):
        lines.append("const struct wb_case_simple %s[] = {" % name)
        for point in sorted(table):
            lines.append("\t{ 0x%05X, 0x%05X }," % (point, table[point]))
        lines.append("};")
        lines.append("const size_t %s_count = sizeof(%s) / sizeof(%s[0]);" % (name, name, name))
        lines.append("")

    def full(name, table):
        lines.append("const struct wb_case_full %s[] = {" % name)
        for point in sorted(table):
            points = table[point] + [0] * (3 - len(table[point]))
            lines.append("\t{ 0x%05X, %d, { 0x%05X, 0x%05X, 0x%05X } }," % (point, len(table[point]), *points))
        lines.append("};")
        lines.append("const size_t %s_count = sizeof(%s) / sizeof(%s[0]);" % (name, name, name))
        lines.append("")

    def range_table(name, points):
        lines.append("const struct wb_code_range %s[] = {" % name)
        for first, last in ranges(points):
            lines.append("\t{ 0x%05X, 0x%05X }," % (first, last))
        lines.append("};")
        lines.append("const size_t %s_count = sizeof(%s) / sizeof(%s[0]);" % (name, name, name))
        lines.append("")

    simple("wb_case_lower", lower)
    simple("wb_case_upper", upper)
    full("wb_case_lower_full", lower_full)
    full("wb_case_upper_full", upper_full)
    range_table("wb_case_cased", cased)
    range_table("wb_case_ignorable", ignorable)
    with open(output, "w", encoding="utf-8") as stream:
        stream.write("\n".join(lines))


if __name__ == "__main__":
    main()
