# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent FreeBSD build of settings; source membership mirrors the target package.
KEILAND_FREEBSD_SETTINGS_SOURCES := userland/desktop/settings/main.c \
	userland/desktop/settings/window.c \
	userland/desktop/settings/present.c \
	userland/desktop/settings/glass.c \
	userland/desktop/settings/titlebar.c \
	userland/desktop/settings/menu.c \
	userland/desktop/settings/ui.c \
	userland/desktop/settings/widgets.c \
	userland/desktop/settings/glyphs.c \
	userland/desktop/settings/pages.c \
	userland/desktop/settings/about.c \
	userland/desktop/settings/page-home.c \
	userland/desktop/settings/page-about.c \
	userland/desktop/settings/page-soon.c \
	userland/desktop/settings/page-network.c \
	userland/desktop/settings/network.c \
	userland/desktop/settings/search.c \
	userland/desktop/settings/look.c \
	userland/desktop/settings/page-look.c \
	userland/desktop/settings/page-input.c \
	userland/desktop/settings/sound.c \
	userland/desktop/files/canvas.c \
	userland/desktop/files/text.c \
	userland/desktop/files/icons.c \
	userland/desktop/artwork/mark.c
$(eval $(call KEILAND_FREEBSD_PROGRAM,settings,bin,$(KEILAND_FREEBSD_SETTINGS_SOURCES),libkeiland.so libwayland-client.so libtruetype.so libvulkan.so.1,-lm -pthread))
