/* Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib */
function check(ok,name){console.log((ok?'PASS ':'FAIL ')+name);ownerVerify(ok);}
var html='http://www.w3.org/1999/xhtml',svg='http://www.w3.org/2000/svg';
document.appendChild(document.createElement('html'));document.documentElement.appendChild(document.createElement('body'));
var listed=['button','fieldset','input','object','output','select','textarea'];
for(var j=0;j<listed.length;j++){var e=document.createElement(listed[j]);check(listedControl(e)&&controlMember(e)&&ownerOf(e)===null,'listed category '+listed[j]);}
var nonlisted=['div','form','img','label','option','optgroup','progress','meter','keygen','legend','a'];
for(var j=0;j<nonlisted.length;j++)check(!listedControl(document.createElement(nonlisted[j]))&&!controlMember(document.createElement(nonlisted[j])),'nonlisted category '+nonlisted[j]);
check(!listedControl(document.createElementNS(svg,'input'))&&!controlMember(document.createElementNS(svg,'input')),'foreign input excluded');
check(!listedControl(document.createElementNS(html,'INPUT'))&&!controlMember(document.createElementNS(html,'INPUT')),'XML uppercase input excluded');
var control=document.createElement('input');control.setAttribute('type','ImAgE');check(listedControl(control)&&!controlMember(control),'image is listed but not controls member');
control.setAttribute('type',' image');check(controlMember(control),'invalid whitespace type remains member');
control.setAttribute('type','hidden');control.setAttribute('disabled','');check(controlMember(control),'hidden disabled unnamed control included');
var outer=document.createElement('form'),inner=document.createElement('form'),wrapper=document.createElement('div');outer.id='outer';inner.id='inner';document.body.appendChild(outer);document.body.appendChild(inner);outer.appendChild(wrapper);wrapper.appendChild(control);
check(ownerOf(control)===outer,'nearest actual form ancestor');
wrapper.appendChild(inner);inner.appendChild(control);check(ownerOf(control)===inner,'script nested form is nearest');
outer.appendChild(control);check(ownerOf(control)===outer,'moving control updates owner');
outer.removeChild(control);check(ownerOf(control)===null,'detached control has no owner');
inner.appendChild(control);check(ownerOf(control)===inner,'reinserted control updates owner');
control.setAttribute('form','outer');check(ownerOf(control)===outer,'connected explicit attribute overrides nearest ancestor');
control.setAttribute('form','missing');check(ownerOf(control)===null,'missing connected explicit id has no ancestor fallback');
control.setAttribute('form','');check(ownerOf(control)===null,'empty connected explicit attribute has no ancestor fallback');
control.setAttribute('form','OUTER');check(ownerOf(control)===null,'explicit form id matching case sensitive');
control.setAttribute('form','outer');outer.id='changed';check(ownerOf(control)===null,'owner id mutation invalidates explicit reference');
outer.id='outer';check(ownerOf(control)===outer,'owner id restoration observed');
var duplicate=document.createElement('div');duplicate.id='outer';document.body.insertBefore(duplicate,outer);check(ownerOf(control)===null,'first duplicate id on nonform suppresses later form');
document.body.removeChild(duplicate);check(ownerOf(control)===outer,'removing duplicate id restores explicit owner');
var foreign=document.createElementNS(svg,'form');foreign.id='outer';document.body.insertBefore(foreign,outer);check(ownerOf(control)===null,'first foreign form id suppresses later HTML form');
document.body.removeChild(foreign);
var second=document.createElement('form');second.id='outer';document.body.insertBefore(second,outer);check(ownerOf(control)===second,'first duplicate actual form wins');
document.body.appendChild(second);check(ownerOf(control)===outer,'form reordering updates first id owner');
control.removeAttribute('form');check(ownerOf(control)===inner,'form attribute removal restores nearest ancestor');
control.setAttribute('form','outer');document.body.removeChild(outer);check(ownerOf(control)===inner,'detached explicit control falls back to nearest form');
check(ownerOf(inner)===null,'form element itself is not associated');
var image=document.createElement('img');image.setAttribute('form','missing');inner.appendChild(image);check(ownerOf(image)===inner,'nonlisted image ignores explicit form attribute');
var unrelated=document.createElement('div');inner.appendChild(unrelated);check(ownerOf(unrelated)===null,'ordinary div has no form owner');
var fragment=document.createDocumentFragment(),detached=document.createElement('form'),detachedInput=document.createElement('input');detached.id='detached';fragment.appendChild(detached);detached.appendChild(detachedInput);detachedInput.setAttribute('form','missing');
check(ownerOf(detachedInput)===detached,'DocumentFragment disconnected explicit reference falls back');
document.body.appendChild(fragment);check(ownerOf(detachedInput)===null,'fragment insertion makes explicit attribute connected');
detachedInput.setAttribute('form','detached');check(ownerOf(detachedInput)===detached,'connected referenced fragment form resolves');
detached.id='renamedDetached';check(ownerOf(detachedInput)===null,'connected fragment form id change observed');
var x=document.implementation.createDocument(null,'Root'),xf=x.createElementNS(html,'form'),xi=x.createElementNS(html,'input');xf.id='xmlForm';x.documentElement.appendChild(xf);x.documentElement.appendChild(xi);xi.setAttribute('form','xmlForm');
check(ownerOf(xi)===xf,'connected XML HTML namespace explicit form');
var xu=x.createElementNS(html,'FORM');xu.id='xmlForm';x.documentElement.insertBefore(xu,xf);check(ownerOf(xi)===null,'XML uppercase first id is not actual form');
x.documentElement.removeChild(xu);xf.appendChild(xi);xi.removeAttribute('form');check(ownerOf(xi)===xf,'XML actual HTML ancestor form');
var xn=x.createElement('form');xn.appendChild(xi);check(ownerOf(xi)===null,'null namespace form ancestor excluded');
var f=document.createElement('iframe');document.body.appendChild(f);var child=f.contentDocument,cf=child.createElement('form'),ci=child.createElement('input');cf.id='childForm';child.body.appendChild(cf);child.body.appendChild(ci);ci.setAttribute('form','childForm');
check(ownerOf(ci)===cf,'managed child owner lookup independent from caller Document');
document.body.removeChild(f);check(ownerOf(ci)===cf,'retired child remains a connected Document tree');
var repeated=true;for(var k=0;k<1000;k++){if(ownerOf(ci)!==cf||!listedControl(ci)||!controlMember(ci))repeated=false;}check(repeated,'repeated allocation-free owner and predicate queries');
check(ownerOf(image)===inner,'other Document changes preserve detached ancestry');
console.log('form owner script done');
