#!/usr/bin/env python3
# Prints WS131's rename maps as Markdown tables (design.md section 5, the 2026-10-03 naming rule).
#   python3 plan/ws131/tools/rename-map.py public > plan/ws131/rename-map.md          (keiui.h and keiland.h -> kl_ / KL_)
#   python3 plan/ws131/tools/rename-map.py compositor > plan/ws131/rename-map-kwl.md  (zwl_ / ZWL_ -> kwl_ / KWL_)
# Run from the repository root.  The maps are generated, never edited by hand; a rename Phase applies them mechanically.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
import re
import sys
from pathlib import Path

KEIUI = Path('userland/desktop/keiland/keiui.h')
KEILAND = Path('userland/desktop/keiland/keiland.h')
PATHS = Path('userland/desktop/paths.h')
COMPOSITOR = Path('userland/desktop/wayland')

# Where two old names would meet in the one kl_ name space, which old name takes which new name.
SPECIAL = {
    'kui_version': ('(removed)', 'kl_version() (from keiland_version) is the one version call'),
    'KUI_VERSION': ('(removed)', 'KL_VERSION (from KEILAND_VERSION) is the one version macro; not raised (2026-10-03 user: ABI may change)'),
    'kui_edit_fn': ('kl_window_edit_fn', 'kl_edit_fn is keiland_edit_fn (void, uint32_t); the window callback differs'),
    'kui_keyboard_inset_fn': ('kl_window_keyboard_inset_fn', 'kl_keyboard_inset_fn is keiland_keyboard_inset_fn; the window callback differs'),
}


def kinds_of(path, prefix_lower, prefix_upper):
    """Returns {name: [kinds, first line, value]} for every prefixed name a header declares or uses outside comments."""
    names = {}
    in_enum = False
    in_comment = False
    pattern = r'\b(?:%s|%s)_[A-Za-z0-9_]+\b' % (prefix_lower, prefix_upper)
    for number, line in enumerate(path.read_text().splitlines(), 1):
        code = line
        if in_comment:
            if '*/' not in code:
                continue
            code = code.split('*/', 1)[1]
            in_comment = False
        code = re.sub(r'/\*.*?\*/', '', code)
        if '/*' in code:
            code = code.split('/*', 1)[0]
            in_comment = True
        if re.match(r'\s*enum %s_\w+\s*\{' % prefix_lower, code):
            in_enum = True
        elif in_enum and code.startswith('}'):
            in_enum = False
        define = re.match(r'#define\s+(%s_[A-Z0-9_]+)\s+(\S+)' % prefix_upper, code)
        for name in re.findall(pattern, code):
            entry = names.setdefault(name, [[], number, None])
            kind = None
            if define and name == define.group(1):
                kind = 'macro'
                entry[2] = define.group(2)
            elif in_enum and re.match(r'\s*' + name + r'\b', code):
                kind = 'enum constant'
            elif re.search(r'\bstruct ' + name + r'\b', code):
                kind = 'struct'
            elif re.search(r'\benum ' + name + r'\b', code):
                kind = 'enum'
            elif re.search(r'typedef[^;]*\b' + name + r'\b', code):
                kind = 'typedef'
            elif re.search(r'\b' + name + r'\s*\(', code):
                kind = 'function'
            if kind is not None and kind not in entry[0]:
                entry[0].append(kind)
    return {n: e for n, e in names.items() if e[0]}


def public():
    keep = set(re.findall(r'#define\s+(KEILAND_[A-Z0-9_]+)', PATHS.read_text()))
    rows = []
    targets = {}
    for path, lower, upper in ((KEILAND, 'keiland', 'KEILAND'), (KEIUI, 'kui', 'KUI')):
        for name, (kinds, line, value) in sorted(kinds_of(path, lower, upper).items(), key=lambda i: (i[0][0].isupper(), i[0])):
            if name in keep:
                continue
            if name in SPECIAL:
                new, note = SPECIAL[name]
            else:
                new = re.sub(r'^%s_' % lower, 'kl_', re.sub(r'^%s_' % upper, 'KL_', name))
                note = ''
            rows.append([name, ', '.join(kinds), new, '%s:%d' % (path.name, line), note, value])
            if not new.startswith('('):
                targets.setdefault(new, []).append(len(rows) - 1)
    collisions = 0
    for new, indexes in targets.items():
        if len(indexes) < 2:
            continue
        values = {rows[i][5] for i in indexes}
        olds = ', '.join('`%s`' % rows[i][0] for i in indexes)
        for i in indexes:
            if len(values) == 1 and None not in values:
                rows[i][4] = 'same value as ' + olds + ': one definition'
            else:
                rows[i][4] = 'COLLISION among ' + olds
                collisions += 1
    for row in rows:
        if row[2].startswith('kl_file_chooser') and row[0].startswith('kui_') and not row[4]:
            row[4] = 'reuses the name of the KEILAND_VERSION 12-15 chooser (removed in 16)'
    kept = '・'.join('`%s`' % k for k in sorted(keep) if not k.endswith('_H'))
    print('<!-- generated by plan/ws131/tools/rename-map.py public; do not edit by hand -->')
    print()
    print('# WS131: 公開の名前の対応表（`keiland_`・`kui_` → `kl_`、`KEILAND_`・`KUI_` → `KL_`）')
    print()
    print('正本は [design.md §5](design.md)。2026-10-03 のユーザーの最終の規則: 関数・型・変数は `kl_`、macro と enum の定数は `KL_`。'
          '`userland/desktop/paths.h` の install の path の macro（%s）はそのまま。'
          '対象は公開の header の `keiland.h` と `keiui.h` が comment の外に書く名前。'
          'Wayland の protocol の識別子（`keiland_*_v1`・`KEILAND_*_V1_*`）と、app・libbrowser の include guard はこの表の外'
          '（design.md §5.2、判断 D15・D16）。' % kept)
    print()
    counts = {}
    for row in rows:
        source = row[3].split(':')[0]
        counts[source] = counts.get(source, 0) + 1
    print('件数: ' + '、'.join('%s %d' % (k, v) for k, v in sorted(counts.items())) +
          '（合計 %d、解決の要る衝突 %d）' % (len(rows), collisions))
    print()
    print('| 旧名 | 種類 | 新名 | 宣言 | 注 |')
    print('| --- | --- | --- | --- | --- |')
    for name, kind, new, where, note, value in rows:
        print('| `%s` | %s | `%s` | %s | %s |' % (name, kind, new, where, note))


def compositor():
    names = {}
    for path in sorted(COMPOSITOR.rglob('*.[ch]')):
        for number, line in enumerate(path.read_text().splitlines(), 1):
            for name in re.findall(r'\b(?:zwl|ZWL)_[A-Za-z0-9_]+\b', line):
                entry = names.setdefault(name, [str(path.relative_to(COMPOSITOR)), number, 0])
                entry[2] += 1
    print('<!-- generated by plan/ws131/tools/rename-map.py compositor; do not edit by hand -->')
    print()
    print('# WS131: compositor の内部の名前の対応表（`zwl_` → `kwl_`、`ZWL_` → `KWL_`）')
    print()
    print('正本は [design.md §5.6](design.md)。`userland/desktop/wayland/` の全ての `.c`・`.h` に出る名前（comment の中を含む）。'
          '数は今の tree の出現の数。backend へ移る境界の名前（`zwl_os_*`・`zwl_input_device_*`・`zwl_gpu_*` など）は移動の Phase で'
          ' `kl_backend_*` になり、改名の Phase の時にはこの表から減る。'
          'log の文字列の接頭辞 `"ZWL "` はこの表の外で、別の Phase が試験と一緒に変える。')
    print()
    lower = sum(1 for n in names if n.startswith('zwl_'))
    print('件数: `zwl_` %d、`ZWL_` %d（合計 %d）' % (lower, len(names) - lower, len(names)))
    print()
    print('| 旧名 | 新名 | 最初の出現 | 出現の数 |')
    print('| --- | --- | --- | --- |')
    for name in sorted(names, key=lambda n: (n[0].isupper(), n)):
        where, line, count = names[name]
        new = 'kwl_' + name[4:] if name.startswith('zwl_') else 'KWL_' + name[4:]
        print('| `%s` | `%s` | %s:%d | %d |' % (name, new, where, line, count))


if __name__ == '__main__':
    if len(sys.argv) != 2 or sys.argv[1] not in ('public', 'compositor'):
        sys.exit('usage: rename-map.py public|compositor')
    if sys.argv[1] == 'public':
        public()
    else:
        compositor()
