# The FreeBSD side of libkeiland-backend (WS131, plan/ws131/design.md section 3.6): a static library the
# compositor links (and libkeiland, while it forwards its old network and sound calls here, until ws131-p011).
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
KEILAND_FREEBSD_BACKEND_SOURCES := userland/desktop/libkeiland-backend/backend.c \
	userland/desktop/libkeiland-backend/wpa/network-wpa.c \
	userland/desktop/libkeiland-backend/wpa/network-config-wpa.c \
	userland/desktop/libkeiland-backend-freebsd/network-link-freebsd.c \
	userland/desktop/libkeiland-backend-freebsd/audio-freebsd.c \
	userland/desktop/libkeiland-backend/unsupported/power-unsupported.c
$(eval $(call KEILAND_FREEBSD_STATIC,keiland-backend,libkeiland-backend.a,$(KEILAND_FREEBSD_BACKEND_SOURCES)))
