# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent Linux build of textedit; source membership mirrors the target package.
KEILAND_LINUX_TEXTEDIT_SOURCES := userland/desktop/textedit/main.c \
	userland/desktop/textedit/queue.c \
	userland/desktop/textedit/menu.c \
	userland/desktop/textedit/titlebar.c \
	userland/desktop/textedit/glass.c \
	userland/desktop/textedit/app.c \
	userland/desktop/textedit/edit.c \
	userland/desktop/textedit/draw.c \
	userland/desktop/textedit/buffer.c \
	userland/desktop/textedit/undo.c \
	userland/desktop/textedit/file.c \
	userland/desktop/textedit/layout.c \
	userland/desktop/textedit/find.c \
	userland/desktop/textedit/canvas.c \
	userland/desktop/textedit/text.c \
	userland/desktop/picture/color-glyph.c
$(eval $(call KEILAND_LINUX_PROGRAM,textedit,bin,$(KEILAND_LINUX_TEXTEDIT_SOURCES),libkeiui.so libkeiland.so libtruetype.so libpng-compat.so libz-compat.so libwayland-client.so libvulkan.so.1,-lm))
