# The native FreeBSD build of libpng-compat.so; the zedBSD build remains in Makefile.
# Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
KEILAND_FREEBSD_PNG_COMPAT_SOURCES := userland/base/libpng-compat/read.c
$(eval $(call KEILAND_FREEBSD_LIBRARY,png-compat,libpng-compat.so,$(KEILAND_FREEBSD_PNG_COMPAT_SOURCES),libz-compat.so,-lm,userland/base/libpng-compat/exports.map))
