# zedBSD; Copyright (C) 2026 Awe Morris; SPDX-License-Identifier: Zlib
# The independent Linux build of kuidemo; source membership mirrors the target package.
KEILAND_LINUX_KUIDEMO_SOURCES := userland/tests/kuidemo/main.c
$(eval $(call KEILAND_LINUX_PROGRAM,kuidemo,bin,$(KEILAND_LINUX_KUIDEMO_SOURCES),libkeiui.so libkeiland.so libwayland-client.so libtruetype.so libvulkan.so.1,-lm))
